var places = ["London", "Saudia", "Dubai", "America", "Turkey"];
console.log(places);
places.sort();
console.log(places);
places.reverse();
console.log(places);
places.reverse();
console.log(places);
places.reverse();
console.log(places);
places.sort();
console.log(places);
places.sort();
console.log(places);
