var colour = "Green";
console.log("Is colour == Green? I predict True.");
console.log(colour == "Green");
console.log("Is colour != Green? I predict True.");
console.log(colour != "Green");
var planet = "JUPITER";
console.log("Is planet.toLowercase() == JUPITER? I predict False.");
console.log(planet.toLowerCase() == "JUPITER");
console.log("Is planet.toLowercase == jupiter? I predict True.");
console.log(planet.toLowerCase() == "jupiter");
var number = 15;
console.log("Is number != 15? I predict True.");
console.log(number != 15);
console.log("Is number == 15? I predict False.");
console.log(number == 15);
console.log("Is number < 3? I predict False.");
console.log(number < 3);
console.log("Is number > 12? I predict True.");
console.log(number > 12);
console.log("Is number >= 20? I predict True.");
console.log(number >= 20);
console.log("Is number <= 10? I predict True.");
console.log(number <= 10);
var on = true;
var off = false;
console.log("Is bulb on || off ? I predict false.");
console.log(on || off);
var day = false;
var night = true;
console.log("Is it day && night? I predict false.");
console.log(day && night);
var sports = ["cricket", "football", "hockey"];
console.log("Is football in  array? I predict True.");
var football = "football";
console.log(sports.includes(football));
