let peoples=["Daniyal","Mawia","Zamad","Areeb","Murtuza"];
console.log("I am able to invite only two peoples for dinner");
peoples.push("Salman");
let p1=peoples.pop();
let p2=peoples.pop();
let p3=peoples.pop();
let p4=peoples.pop();
console.log(`Hello ${p1}, Sorry can't invite you for dinner tonight`);
console.log(`Hello ${p2}, Sorry can't invite you for dinner tonight`);
console.log(`Hello ${p3}, Sorry can't invite you for dinner tonight`);
console.log(`Hello ${p4}, Sorry can't invite you for dinner tonight`);